package saelastic

//ProceventMapping ...
const ProceventMapping = `
{
"procevent":{
   "mappings":{
      "event":{
         "properties":{
            "annotations":{
               "properties":{
                  "summary":{
                     "type":"text",
                     "fields":{
                        "keyword":{
                           "type":"keyword",
                           "ignore_above":256
                        }
                     }
                  },
                  "ves":{
                     "properties":{
                        "domain":{
                           "type":"text",
                           "fields":{
                              "keyword":{
                                 "type":"keyword",
                                 "ignore_above":256
                              }
                           }
                        },
                        "eventId":{
                           "type":"long"
                        },
                        "eventName":{
                           "type":"text",
                           "fields":{
                              "keyword":{
                                 "type":"keyword",
                                 "ignore_above":256
                              }
                           }
                        },
                        "faultFields":{
                           "properties":{
                              "alarmCondition":{
                                 "type":"text",
                                 "fields":{
                                    "keyword":{
                                       "type":"keyword",
                                       "ignore_above":256
                                    }
                                 }
                              },
                              "alarmInterfaceA":{
                                 "type":"text",
                                 "fields":{
                                    "keyword":{
                                       "type":"keyword",
                                       "ignore_above":256
                                    }
                                 }
                              },
                              "eventSeverity":{
                                 "type":"text",
                                 "fields":{
                                    "keyword":{
                                       "type":"keyword",
                                       "ignore_above":256
                                    }
                                 }
                              },
                              "eventSourceType":{
                                 "type":"text",
                                 "fields":{
                                    "keyword":{
                                       "type":"keyword",
                                       "ignore_above":256
                                    }
                                 }
                              },
                              "faultFieldsVersion":{
                                 "type":"float"
                              },
                              "specificProblem":{
                                 "type":"text",
                                 "fields":{
                                    "keyword":{
                                       "type":"keyword",
                                       "ignore_above":256
                                    }
                                 }
                              },
                              "vfStatus":{
                                 "type":"text",
                                 "fields":{
                                    "keyword":{
                                       "type":"keyword",
                                       "ignore_above":256
                                    }
                                 }
                              }
                           }
                        },
                        "lastEpochMicrosec":{
                           "type":"long"
                        },
                        "priority":{
                           "type":"text",
                           "fields":{
                              "keyword":{
                                 "type":"keyword",
                                 "ignore_above":256
                              }
                           }
                        },
                        "reportingEntityName":{
                           "type":"text",
                           "fields":{
                              "keyword":{
                                 "type":"keyword",
                                 "ignore_above":256
                              }
                           }
                        },
                        "sequence":{
                           "type":"long"
                        },
                        "sourceName":{
                           "type":"text",
                           "fields":{
                              "keyword":{
                                 "type":"keyword",
                                 "ignore_above":256
                              }
                           }
                        },
                        "startEpochMicrosec":{
                           "type":"long"
                        },
                        "version":{
                           "type":"float"
                        }
                     }
                  }
               }
            },
            "labels":{
               "properties":{
                  "alertname":{
                     "type":"text",
                     "fields":{
                        "keyword":{
                           "type":"keyword",
                           "ignore_above":256
                        }
                     }
                  },
                  "instance":{
                     "type":"text",
                     "fields":{
                        "keyword":{
                           "type":"keyword",
                           "ignore_above":256
                        }
                     }
                  },
                  "procevent":{
                     "type":"text",
                     "fields":{
                        "keyword":{
                           "type":"keyword",
                           "ignore_above":256
                        }
                     }
                  },
                  "service":{
                     "type":"text",
                     "fields":{
                        "keyword":{
                           "type":"keyword",
                           "ignore_above":256
                        }
                     }
                  },
                  "severity":{
                     "type":"text",
                     "fields":{
                        "keyword":{
                           "type":"keyword",
                           "ignore_above":256
                        }
                     }
                  },
                  "type":{
                     "type":"text",
                     "fields":{
                        "keyword":{
                           "type":"keyword",
                           "ignore_above":256
                        }
                     }
                  }
               }
            },
            "startsAt":{
               "type":"date"
            }
         }
      }
   }
}
}
}`
