package saelastic


//SyseventMapping ...
const SyseventMapping = `
{
   "sysevent":{
      "mappings":{
         "event":{
            "properties":{
               "annotations":{
                  "properties":{
                     "summary":{
                        "type":"text",
                        "fields":{
                           "keyword":{
                              "type":"keyword",
                              "ignore_above":256
                           }
                        }
                     },
                     "ves":{
                        "properties":{
                           "domain":{
                              "type":"text",
                              "fields":{
                                 "keyword":{
                                    "type":"keyword",
                                    "ignore_above":256
                                 }
                              }
                           },
                           "eventId":{
                              "type":"long"
                           },
                           "eventName":{
                              "type":"text",
                              "fields":{
                                 "keyword":{
                                    "type":"keyword",
                                    "ignore_above":256
                                 }
                              }
                           },
                           "lastEpochMicrosec":{
                              "type":"long"
                           },
                           "priority":{
                              "type":"text",
                              "fields":{
                                 "keyword":{
                                    "type":"keyword",
                                    "ignore_above":256
                                 }
                              }
                           },
                           "reportingEntityName":{
                              "type":"text",
                              "fields":{
                                 "keyword":{
                                    "type":"keyword",
                                    "ignore_above":256
                                 }
                              }
                           },
                           "sequence":{
                              "type":"long"
                           },
                           "sourceName":{
                              "type":"text",
                              "fields":{
                                 "keyword":{
                                    "type":"keyword",
                                    "ignore_above":256
                                 }
                              }
                           },
                           "startEpochMicrosec":{
                              "type":"long"
                           },
                           "syslogFields":{
                              "properties":{
                                 "eventSourceHost":{
                                    "type":"text",
                                    "fields":{
                                       "keyword":{
                                          "type":"keyword",
                                          "ignore_above":256
                                       }
                                    }
                                 },
                                 "eventSourceType":{
                                    "type":"text",
                                    "fields":{
                                       "keyword":{
                                          "type":"keyword",
                                          "ignore_above":256
                                       }
                                    }
                                 },
                                 "syslogFieldsVersion":{
                                    "type":"float"
                                 }
                              }
                           },
                           "syslogMsg":{
                              "type":"text",
                              "fields":{
                                 "keyword":{
                                    "type":"keyword",
                                    "ignore_above":256
                                 }
                              }
                           },
                           "syslogProc":{
                              "type":"text",
                              "fields":{
                                 "keyword":{
                                    "type":"keyword",
                                    "ignore_above":256
                                 }
                              }
                           },
                           "syslogSev":{
                              "type":"text",
                              "fields":{
                                 "keyword":{
                                    "type":"keyword",
                                    "ignore_above":256
                                 }
                              }
                           },
                           "syslogTag":{
                              "type":"text",
                              "fields":{
                                 "keyword":{
                                    "type":"keyword",
                                    "ignore_above":256
                                 }
                              }
                           },
                           "version":{
                              "type":"float"
                           }
                        }
                     }
                  }
               },
               "labels":{
                  "properties":{
                     "alertname":{
                        "type":"text",
                        "fields":{
                           "keyword":{
                              "type":"keyword",
                              "ignore_above":256
                           }
                        }
                     },
                     "instance":{
                        "type":"text",
                        "fields":{
                           "keyword":{
                              "type":"keyword",
                              "ignore_above":256
                           }
                        }
                     },
                     "service":{
                        "type":"text",
                        "fields":{
                           "keyword":{
                              "type":"keyword",
                              "ignore_above":256
                           }
                        }
                     },
                     "severity":{
                        "type":"text",
                        "fields":{
                           "keyword":{
                              "type":"keyword",
                              "ignore_above":256
                           }
                        }
                     }
                  }
               },
               "startsAt":{
                  "type":"date"
               }
            }
         }
      }
   }
}`
